### ISSUE TITLE
zzuf can't handle /dev/zero char device on modern glibc (tutorial uses it)

### ISSUE THREAD

**Issue by trofi** [samhocevar/zzuf#19]
Popped up in https://bugs.gentoo.org/show_bug.cgi?id=613130 where
user tried first example from tutorial:
```
zzuf hexdump -vn 32 /dev/zero 
0000000 0000 0000 0000 0000 0000 0000 0000 0000
0000010 0000 0000 0000 0000 0000 0000 0000 0000
0000020
```

Unfortunately `/dev/zero` is not handled nicely by (at leat) `glibc-2.24`:

```c
// $ cat a.c
  #include <stdio.h>

  int main() {
    FILE * f = fopen("/dev/zero", "r");
    char b[15];

    long o1 = ftell (f);
    fread (b, 1, sizeof (b), f);
    long o2 = ftell (f);

    printf ("advanced at = %lu [%li/%li]\n", o2 - o1, o1, o2);
    return 0;
  }
```
```
$ gcc a.c -o a && ./a 
  advanced at = 18446744073709551615 [0/-1]
```

zzuf has a few FIXMEs around this case:
```
  src/libzzuf/lib-stream.c:        /* FIXME: ftell() will return -1 on a pipe such as stdin */ \
  src/libzzuf/lib-stream.c:        /* FIXME: ftell() will return -1 on a pipe such as stdin */ \
  src/libzzuf/lib-stream.c:        /* FIXME: ftell() will return -1 on a pipe such as stdin */ \
  src/libzzuf/lib-stream.c:        /* FIXME: ftell() will return -1 on a pipe such as stdin */ \
```

I suggest tweaking tutorial to use normal file and adding a warnings into zzuf when
`ZZ_FTELL` returns negative values.

WDYT?

Thanks!

**Comment by JulianVolodia** [comment]
With regards to Gentoo post, maybe adding reference on which glibc that was working as described in tutorial?

**Comment by trofi** [comment]
I don't know a working version of kernel/libc. In theory it might not work at all ever.

A few heuristics: looking at http://caca.zoy.org/wiki/zzuf/tutorial1?action=history it was documented 11 years ago (~year 2008).

- https://sourceware.org/glibc/wiki/Glibc%20Timeline suggests it might be around glibc-2.8 
- https://kernelnewbies.org/LinuxVersions suggests it might be around 2.6.24
