### ISSUE TITLE
consider adding a new release version like 0.14 + git tags

### ISSUE THREAD

**Issue by anthraxx** [samhocevar/zzuf#2]
Hey, first: thanks for this great project :smile: 

the last announced release is kind of old (zzuf-0.13.tar.gz (31 January 2010)). It would be cool if you could create a new release like 0.14.
I would highly appreciate if you can create a git tag for that, as github offers source tarballs for tags (which are great for downloading sources for packages).
Also you may want to update the ancient version provided at http://caca.zoy.org/wiki/zzuf

This would ease packaging zzuf :+1: 

cheers
anthraxx

**Comment by samhocevar** [comment]
Sure, no problem! This is coming soon (tags are already there).

**Comment by anthraxx** [comment]
@samhocevar wow awesome news :+1: thank you a lot mate!
Just small hint as you said "tags are already there"... did you maybe forget to 'git push --tags' ? :yum: or is that what you mean with "comming soon"? Just wanted to point it out in case its by accident :yum: 
cheers

**Comment by samhocevar** [comment]
I pushed the tags minutes before I left the above comment. The Github website sees them; don’t you?

**Comment by anthraxx** [comment]
@samhocevar maybe I'm just stupid but where? I can't see the tag at https://github.com/samhocevar/zzuf/releases (only the old 0.13) also
> git ls-remote https://github.com/samhocevar/zzuf
does not list them for me. Am i stupid? :smile:

**Comment by samhocevar** [comment]
Oh, I didn’t mean to say there was a 0.14 tag or release yet, just that there were tags! I’m still working on 0.14.

**Comment by anthraxx** [comment]
ok then I just misunderstood your sentence, my bad :smile: 
thank you very much for the first step, looking forward for 0.14 :smiley:

**Comment by samhocevar** [comment]
All done! Let me know of any issues you may come across.
