### ISSUE TITLE
common/fd.c:381 logical fault ?

### ISSUE THREAD

**Issue by dcb314** [samhocevar/zzuf#22]
common/fd.c:383]: (warning) Opposite inner 'if' condition leads to a dead code block.

Source code is

    if (fd >= 0 && fd < maxfd && fds[fd] != -1)
    {
        if (fd == -1)
            ++create_lock;

Inner if can never be executed. Suggest code rework.

**Comment by samhocevar** [comment]
Thanks. I reviewed the commit leading to this code and found the bug.
