### ISSUE TITLE
Memory Exceed on x86 64 bit

### ISSUE THREAD

**Issue by ya1gaurav** [samhocevar/zzuf#9]
Running zzuf on libxml2 on Ububtu x86_64 , always give below issue
zzuf -s 0:10000 -c -C 0 -q -T 3 objdump -x ./xmllint
zzuf[s=244,r=0.004]: signal 9 (memory exceeded?)
zzuf[s=455,r=0.004]: signal 9 (memory exceeded?)
zzuf[s=1163,r=0.004]: signal 9 (memory exceeded?)

It cannot be debugged further.
How to resolve this ?

**Comment by samhocevar** [comment]
You now have to generate a file that will crash `xmllint` without zzuf, using for instance seed 244:

    # zzuf -s 244 < ./xmllint > xmllint.fuzzed
    # objdump -x xmllint.fuzzed
    objdump: xmllint.fuzzed: Memory exhausted
    #

If that specific bug doesn’t interest you, you will need to keep zzuf running until it finds another issue than “memory exceeded”.

**Comment by ya1gaurav** [comment]
`# zzuf -s 244 < ./xmllint > xmllint.fuzzed
# objdump -x xmllint.fuzzed
objdump: xmllint.fuzzed: Memory exhausted
#`
Same thing happend with me, Is this a bug? how to get backtrace ?

**Comment by samhocevar** [comment]
It is the expected workflow. You no longer need zzuf at this point, use `gdb` or some other debugger. Study the objdump source code to find out where the “Memory exhauster” message comes from and add a breakpoint there, for instance.

**Comment by ya1gaurav** [comment]
ok

**Comment by ya1gaurav** [comment]
how can I make fuzzed xml file using zzuf ? because xmllint expect some input xml file to parse.

**Comment by ya1gaurav** [comment]
and if I give command like below:
 zzuf -s 0:10000 -c -C 0 -q -T 3 objdump -x ./xmllint ./test/title.xml
will title.xml be considered as input to xmllint?

**Comment by samhocevar** [comment]
No, since the beginning you are fuzzing `objdump`, not `xmllint`. If you want to fuzz `xmllint` you need something like this:

    zzuf -s 0:10000 -c -C 0 -q -T 3 ./xmllint ./test/title.xml

**Comment by ya1gaurav** [comment]
and how to fuzz just xml file?
My intention is to fuzz a xml file & then use fuzzy xml input to xmllint.

**Comment by samhocevar** [comment]
Have you read the documentation, and especially the presentations linked [on the web page](http://caca.zoy.org/wiki/zzuf)? Fuzzing isn’t easy, you probably need solid knowledge of file formats and how your application works first.

**Comment by JulianVolodia** [comment]
@ya1gaurav as you could find it on web, mem exhaust is not considered a bug (in more than most cases).

https://sourceware.org/bugzilla/show_bug.cgi?id=23771

If you found this objdump one-liner and want to dumb-fuzz like in [this tutorial](https://fuzzing-project.org/tutorial1.html) (your call look similar to 1st stage of tutorial involving zzuf there), remember that you must use unpatched version to see the bug. Like they said: `Please note: If you fuzzed one of the example applications mentioned here a large number of issues have *already been reported there and the authors are busy fixing them.* If you want to report anything make sure you test the crashes with their latest upstream git/svn code.`

Fuzzing isn't hard thought. Conception is very simple. This is dumb fuzz.  
But way to get fuzzing be effective is not the easiest one.
Complexicity to have coverage of code flow in fuzzed binary, and maybe it's the key for you to learn more about it.

I decided to post it here (3yo question) in sharing and contribution in mind. Maybe somebody going through beginning will find that and seem useful, which help her/him to learn something.
